language: minimal
sudo: required

matrix:
    include:
        - os: linux
          dist: xenial
          services: docker
          script:
            - ./ci.sh
        - os: osx
          osx_image: xcode11.4
          addons:
              homebrew:
                  packages:
                      - libressl
          #env: SWIFT_VERSION=5.0
          #install:
          #  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
          script:
            - swift build

